# Pandas Exercises

In [ ]:
import pandas as pd
import numpy as np

## Task 1

Given:
```python
data = {
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi"],
    "age": [25, 30, 28, 22, 35],
    "salary": [2500, 3200, 2800, 2100, 4000],
    "department": ["IT", "HR", "IT", "Marketing", "IT"]
}
```

Write code that displays:
- The number of rows and columns.
- The column names.
- The DataFrame index.
- The data type of each column.
- The first 3 lines.
- The last 2 lines.
- Get basic statistics

In [ ]:
data = {
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi"],
    "age": [25, 30, 28, 22, 35],
    "salary": [2500, 3200, 2800, 2100, 4000],
    "department": ["IT", "HR", "IT", "Marketing", "IT"]
}

df = pd.DataFrame(data)

print(f"Number of rows and columns: {df.shape}")
print(f"The column names: {df.columns}")
print(f"The DataFrame index: {df.index}")
print(f"The data type of each column:\n{df.dtypes}")
print(f"The first 3 lines:\n{df.head(3)}")
print(f"The last 2 lines:\n{df.tail(2)}")
print(df.describe())

## Task 2 - Series from DataFrame

Given:
```python
data = {
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi"],
    "age": [25, 30, 28, 22, 35],
    "salary": [2500, 3200, 2800, 2100, 4000],
    "department": ["IT", "HR", "IT", "Marketing", "IT"]
}
```

Create two variables:
- ages = ...
- employee_data = ...

where:
- ages contains only the age column;
- employee_data contains the name and salary columns.

Then, check the type of each variable.

In [ ]:
data = {
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi"],
    "age": [25, 30, 28, 22, 35],
    "salary": [2500, 3200, 2800, 2100, 4000],
    "department": ["IT", "HR", "IT", "Marketing", "IT"]
}

df = pd.DataFrame(data)

ages = df["age"]
employee_data = df[["age", "salary"]]

print(ages.dtypes)
print(employee_data.dtypes)

### Task 3 - DataFrame from Scratch

Create a DataFrame from scratch containing at least 5 books, for example:
- title
- author
- year
- price

Then:
- Display the first 3 books.
- Display the last 2.
- Display the column names.
- Display the dimensions of the DataFrame.
- Display the column data types.
- Display statistics for the numerical columns.

In [ ]:
books = {
    "title": ["The Hobbit", "1984", "Dune", "The Name of the Wind", "The Martian"],
    "author": ["J.R.R. Tolkien", "George Orwell", "Frank Herbert", "Patrick Rothfuss", "Andy Weir"],
    "year": [1937, 1949, 1965, 2007, 2011],
    "price": [14.99, 12.50, 18.99, 16.75, 13.49]
}

books_df = pd.DataFrame(books)

print(f"First 3 books:\n{books_df.head(3)}")
print(f"Last 2 books:\n{books_df.tail(2)}")
print(f"Column names: {books_df.columns}")
print(f"DataFrame dimensions: {books_df.shape}")
print(f"Column data types:\n{books_df.dtypes}")
print(f"Display statistics for the numerical columns:\n{books_df.describe()}")

In [ ]:
df_indexed = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
},
index=["EMP101", "EMP205", "EMP309", "EMP412", "EMP550", "EMP623", "EMP741"]
)

## Task 4

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Use loc to display the first row.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.loc[0]

## Task 5

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Use loc to display the third row.

## Task 6

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```
Display only the name of the person with index 3.

Expected result:
- Anna

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.loc[3, "name"]

## Task 7

Display the name and salary of the person with index 4.

Expected:
- Georgi    4000

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.loc[4, ["name", "salary"]]

## Task 8

Display the rows with indices:

```text
0
2
5
```

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.loc[[0, 2, 5]]

## Task 9

Display only the following columns for rows 1, 3, and 6:
- name
- department

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.loc[[1, 3, 6], ["name", "department"]]

## Task 10

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Use `iloc` to display the first row.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.iloc[0]

## Task 11

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Display the value 2800 using only `iloc`.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.iloc[2, 2]

## Task 12

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```
Using `iloc` to display for Peter:
- name
- salary

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.iloc[2, [0, 2]]

## Task 13

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Using `iloc`, display the first 3 and last 3 rows.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

print(df.iloc[:3])
print(df.iloc[-3:])

## Task 14

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```


Using `iloc`, display all rows, but only:
- name
- salary

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.iloc[:, [0, 2]]

## Task 15

Given:

```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Using `iloc`, display for the first 4 rows:
- name
- age
- salary

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.iloc[: 4, :3]

## Task 16

Given:
```python
df_indexed = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
},
index=["EMP101", "EMP205", "EMP309", "EMP412", "EMP550", "EMP623", "EMP741"]
)
```

Use `loc` and `iloc` to display Peter.

In [ ]:
df_indexed = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
},
index=["EMP101", "EMP205", "EMP309", "EMP412", "EMP550", "EMP623", "EMP741"]
)

print(df_indexed.loc["EMP309"])
print(df_indexed.iloc[2])

## Task 17

Given:
```python
df_indexed = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
},
index=["EMP101", "EMP205", "EMP309", "EMP412", "EMP550", "EMP623", "EMP741"]
)
```

Use `loc` and `iloc` to display Georgi's salary.

In [ ]:
df_indexed = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
},
index=["EMP101", "EMP205", "EMP309", "EMP412", "EMP550", "EMP623", "EMP741"]
)

df_indexed.loc["EMP550", "salary"]
df_indexed.iloc[4, 2]

## Task 18

Given:
```python
df_indexed = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
},
index=["EMP101", "EMP205", "EMP309", "EMP412", "EMP550", "EMP623", "EMP741"]
)
```

Use `loc` and `iloc` to display:
```text
Maria
Peter
Anna
```

In [ ]:
df_indexed = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
},
index=["EMP101", "EMP205", "EMP309", "EMP412", "EMP550", "EMP623", "EMP741"]
)

df_indexed.loc[["EMP205", "EMP309", "EMP412"], "name"]
df.iloc[[1, 2, 3], 0]

## Task 19

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Use:

`df.loc[1:5]` and `df.iloc[1:5]`

and describe which indices you get.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

print(f"df.loc[1:5]:\n{df.loc[1:5]}\n")
print(f"df.iloc[1:5]\n{df.iloc[1:5]}")

## Task 20

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Use `loc` and `iloc` to get:
- Ivan
- Maria
- Peter
- Anna

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

print(f"df.loc:\n{df.loc[:3]}\n")
print(f"df.iloc:\n{df.loc[:4]}")

## Task 21

Given:
```python
df_indexed = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
},
index=["EMP101", "EMP205", "EMP309", "EMP412", "EMP550", "EMP623", "EMP741"]
)
```

For df_indexed, use `loc` and `iloc` to select:
- EMP205 → EMP550

In [ ]:
df_indexed = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
},
index=["EMP101", "EMP205", "EMP309", "EMP412", "EMP550", "EMP623", "EMP741"]
)

print(f"df_indexed.loc:\n{df_indexed.loc["EMP205": "EMP550"]}")
print(f"df_indexed.iloc:\n{df_indexed.iloc[1:5]}")

## Task 22

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Show all employees who are:
- age > 25

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df[df["age"] > 25]

## Task 23

Given:

```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Show all employees who are:
- salary > 3000

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df[df["salary"] > 3000]

## Task 24

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Show all employees from:
- IT

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df[df["department"] == "IT"]

## Task 25

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Show all employees who do not work in IT.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df[df["department"] != "IT"]

## Task 26

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Show the employees who:
- work in IT AND salary > 2800

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df[(df["department"] == "IT") & (df["salary"] > 2800)]

## Task 27

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Show the employees who:
- work in HR OR work in Marketing

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df[(df["department"] == "HR") | (df["department"] == "Marketing")]

## Task 28

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Show the employees who:
- do not work in HR AND salary > 2500

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df[(df["department"] != "HR") & (df["salary"] > 2500)]

## Task 29

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Show only:
- name
- salary   
for employees earning over 3000.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df[df["salary"] > 3000][["name", "salary"]]

## Task 30

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Show only:
- name
- department   
for employees working in IT.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df[df["department"] == "IT"][["name", "department"]]

## Task 31

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```
Show only:
- name
- salary   
for employees who:
- work in IT AND salary >= 2800

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df[(df["department"] == "IT") & (df["salary"] >= 2800)][["name", "salary"]]


## Task 32

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Show:
- name
- department
- salary   

for employees who meet at least one of the following conditions:
- age < 25   
OR
- salary >= 3500   
OR
- work in IT AND salary > 2500

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df[(df["age"] < 25) | (df["salary"] >= 3500) | ((df["department"] == "IT") & (df["salary"] > 2500))][["name", "department", "salary"]]

## Task 33

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Sort the employees by salary in ascending order.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.sort_values(by="salary")

## Task 34

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Sort them by age in descending order.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.sort_values(by="age", ascending=False)

## Task 35

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Sort by department in ascending order, and within each department — by salary in descending order.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.sort_values(by=["department", "salary"], ascending=[True, False])

## Task 36

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

- Create a column `annual_salary` using salary.
- Create a column `salary_after_raise` where everyone receives a 10% raise.
- Add a column `bonus` with a value of 500 for everyone.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df["annual_salary"] = df["salary"] * 12
df["salary_after_raise"] = df["salary"] * 1.1
df["bonus"] = 500
df

## Task 37

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Use `loc` to change Anna's salary to 3000.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df.loc[3, "salary"] = 3000
df

## Task 38

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

Increase the salary of all IT employees by 15%.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df["salary"] = df["salary"].astype(float)

df.loc[
    df["department"] == "IT",
    "salary"
] *= 1.15

## Task 39

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

- Create a Boolean column `is_senior` which is True if age >= 30, otherwise False.
- Remove the `is_senior` column.
- Rename:   
name → employee_name   
salary → monthly_salary

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df["it_senior"] = False
df.loc[
    df["age"] >= 30,
    "it_senior"
] = True

df = df.drop("it_senior", axis = 1)

df = df.rename(
    columns={
        "name": "employee_name",
        "salary": "monthly_salary"
    }
)

df

## Task 40

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```

- Display all unique departments.
- How many different departments are there?
- How many employees are there in each department?

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

print(df["department"].unique())
print(df["department"].nunique())
print(df["department"].value_counts())

## Task 41

Given:
```python
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})
```
- Calculate the percentage of employees working in IT.
- Calculate the percentage working in HR.

In [ ]:
df = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena", "Nikolay"],
    "age": [25, 30, 28, 22, 35, 27, 31],
    "salary": [2500, 3200, 2800, 2100, 4000, 2900, 3500],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing"
    ]
})

df["department"].value_counts(normalize=True) * 100

## Task 42

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})
```

- How many employees are there in each department?
- Find the average salary for each department.
- Find the maximum salary in each department.
- Find the total sum of salaries for each department.
- Find the average age in each department.

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})

df.groupby("department").count()
df.groupby("department")["salary"].mean()
df.groupby("department")["salary"].max()
df.groupby("department")["salary"].sum()
df.groupby("department")["age"].mean()

## Task 42

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})
```

Which department has the highest average salary?

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})

df.groupby("department")["salary"].mean().idxmax()

## Task 42

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})
```

Which department has the lowest average age?

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})

df.groupby("department")["age"].mean().idxmin()

## Task 43

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})
```

Who is the highest-paid employee in each department?

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})

df.loc[df.groupby("department")["salary"].idxmax(), ["department", "name", "salary"]]

## Task 44

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})
```

For each department, find:

average salary
minimum salary
maximum salary

Use a single groupby() rather than three separate operations.

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})

df.groupby("department").agg(
    average_salary = ("salary", "mean"),
    minimum_salary = ("salary", "min"),
    maximum_salary = ("salary", "max")
)

## Task 45

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})
```

Create a table with the following columns:
- department
- average_salary
- minimum_salary
- maximum_salary
- average_age

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})


df.groupby("department").agg(
    average_salary = ("salary", "mean"),
    minimum_salary = ("salary", "min"),
    maximum_salary = ("salary", "max"),
    average_age = ("age", "mean")
)

## Task 46

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})
```

For each department, find:
- the number of employees
- the average years_experience
- the maximum years_experience

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})

df.groupby("department").agg(
    employee_count = ("name", "count"),
    avg_years_experience = ("years_experience", "mean"),
    max_years_experience = ("years_experience", "max")
)

## Task 47

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})
```

Group the employees by:
- department
- age

and count how many employees there are in each combination.

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})

df.groupby(["department", "age"]).count()

## Task 48

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})
```

Group by:
- department
- years_experience

and find the average salary for each combination.

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})

df.groupby(["department", "years_experience"])["salary"].mean()

## Task 49

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})
```

Which department has the most employees with more than 5 years of experience?

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})

df[df["years_experience"] > 5].groupby("department").size().idxmax()

## Task 50

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})
```

Find the average department salary only for employees who are 30 or above.

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})

In [ ]:
df[df["age"] >= 30].groupby("department")["salary"].mean()

## Task 51

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})
```

Find the average department salary of employees with years_experience >= 5

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})

df[df["years_experience"] >= 5].groupby("department")["salary"].mean()

## Task 52

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})
```

Create a DataFrame containing the following for each department:
- employee_count
- average_salary
- minimum_salary
- maximum_salary
- total_salary
- average_experience

Then:
- Sort the result by average_salary in descending order.
- Find the department with the highest average salary.
- Find the department with the highest total salary.

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "department": [
        "IT", "HR", "IT", "Marketing", "IT",
        "HR", "Marketing", "IT", "HR", "Marketing"
    ],
    "age": [
        25, 30, 28, 22, 35,
        27, 31, 29, 34, 26
    ],
    "salary": [
        2500, 3200, 2800, 2100, 4000,
        2900, 3500, 3100, 3700, 2600
    ],
    "years_experience": [
        2, 6, 4, 1, 10,
        4, 7, 5, 9, 3
    ]
})

new_df = df.groupby("department").agg(
    employee_count = ("name", "count"),
    average_salary = ("salary", "mean"),
    minimum_salary = ("salary", "min"),
    maximum_salary = ("salary", "max"),
    total_salary = ("salary", "sum"),
    average_experience = ("years_experience", "mean")
)

new_df.sort_values("average_salary", ascending=False, inplace=True)
new_df["average_salary"].idxmax()
new_df["total_salary"].idxmax()

## Task 53

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "age": [
        25, 30, np.nan, 22, 35,
        27, 31, np.nan, 34, 26
    ],
    "salary": [
        2500, np.nan, 2800, 2100, 4000,
        np.nan, 3500, 3100, np.nan, 2600
    ],
    "department": [
        "IT", "HR", "IT", np.nan, "IT",
        "HR", "Marketing", "IT", np.nan, "Marketing"
    ]
})
```

- Display a Boolean DataFrame showing the locations of missing values.
- Display the number of missing values ​​in each column.
- Find the total number of missing values ​​in the entire DataFrame.
- Calculate the percentage of missing values ​​for each column.
- Display only the employees for whom the salary is missing.
- Display only the employees for whom the department is not missing.

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "age": [
        25, 30, np.nan, 22, 35,
        27, 31, np.nan, 34, 26
    ],
    "salary": [
        2500, np.nan, 2800, 2100, 4000,
        np.nan, 3500, 3100, np.nan, 2600
    ],
    "department": [
        "IT", "HR", "IT", np.nan, "IT",
        "HR", "Marketing", "IT", np.nan, "Marketing"
    ]
})

df.isna()
df.isna().sum()
df.isna().sum().sum()
df.isna().mean() * 100 # type: ignore
df.loc[df["salary"].isna()]
df.loc[df["department"].notna()]

## Task 54

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "age": [
        25, 30, np.nan, 22, 35,
        27, 31, np.nan, 34, 26
    ],
    "salary": [
        2500, np.nan, 2800, 2100, 4000,
        np.nan, 3500, 3100, np.nan, 2600
    ],
    "department": [
        "IT", "HR", "IT", np.nan, "IT",
        "HR", "Marketing", "IT", np.nan, "Marketing"
    ]
})
```

- Remove all rows that contain at least one missing value.
- Remove only the rows where the salary is missing.
- Replace missing department values ​​with "Unknown"
- Replace missing salary values ​​with the average salary.
- Replace missing age values ​​with the median age.
- Find the most frequent department and use its value to fill in the missing departments.

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna", "Georgi",
        "Elena", "Nikolay", "Viktor", "Daniel", "Laura"
    ],
    "age": [
        25, 30, np.nan, 22, 35,
        27, 31, np.nan, 34, 26
    ],
    "salary": [
        2500, np.nan, 2800, 2100, 4000,
        np.nan, 3500, 3100, np.nan, 2600
    ],
    "department": [
        "IT", "HR", "IT", np.nan, "IT",
        "HR", "Marketing", "IT", np.nan, "Marketing"
    ]
})

df.dropna(how="any")
df.dropna(subset="salary")
df["department"].fillna("Unknown")
df["salary"].fillna(df["salary"].mean())
df["age"].fillna(df["age"].median())
df["department"].fillna(df["department"].value_counts().idxmax())

## Task 55

Given:
```python
df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})
```
Show the data type of each column.

In [ ]:
df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})

df.dtypes

## Task 56

Given:
```python
df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})
```

- Convert `salary` from a string to a numeric type.
Then check by using `df.dtypes`

- Calculate the average `salary`.

In [ ]:
df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})


df["salary"] = df["salary"].astype(float)
print(df.dtypes)
df["salary"].mean()

## Task 57

Given:
```python
df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})
```

- Remove extra spaces from `name`.
- Convert all `name` values ​​to lowercase.
- Convert all `department` values ​​to uppercase and remove whitespace.

In [ ]:
df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})

df["name"].str.strip().str.lower()
df["department"].str.strip().str.upper()

## Task 58

Given:
```python
df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})
```

Find all employees whose name contains the letter `a`

In [ ]:
df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})

df[df["name"].str.contains("a")]

df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})

Find all employees whose name starts with `"A"`

In [ ]:
df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})

df.loc[df["name"].str.strip().str.slice(0,1) == "A"]

## Task 59

Given:
```python
df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})
```
Create a new column `name_length` containing the number of characters in the name.

In [ ]:
df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})

df["name_length"] = df["name"].str.strip().str.len()
df

## Task 60

Given:
```python
df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})
```

Replace in the `department` column:
- IT → Information Technology
- HR → Human Resources

In [ ]:
df = pd.DataFrame({
    "name": [
        " Ivan ",
        "MARIA",
        "Peter",
        " anna ",
        "Georgi"
    ],
    "age": [
        25,
        30,
        28,
        22,
        35
    ],
    "salary": [
        "2500",
        "3200",
        "2800",
        "2100",
        "4000"
    ],
    "department": [
        " IT ",
        "HR",
        "it",
        " Marketing ",
        "IT"
    ]
})

df["department"] = df["department"].str.upper().str.replace(
    {"IT": "Information Technology",
     "HR": "Human Resources"}
)

df

## Task 61

Given:
```python
df = pd.DataFrame({
    "name": [
        "  Ivan Petrov ",
        "Maria Ivanova",
        "  PETER SMITH",
        "Anna Brown  ",
        "georgi dimitrov"
    ],
    "salary": [
        "2500",
        "3200",
        "unknown",
        "2100",
        "4000"
    ]
})
```

- Remove whitespace from `name`.
- Format all names in Title Case.
- Convert `salary` to numeric.
- Replace "unknown" with NaN.
- Identify rows with missing `salary`.
- Calculate the average `salary` without filling in the NaN values.

In [ ]:
df = pd.DataFrame({
    "name": [
        "  Ivan Petrov ",
        "Maria Ivanova",
        "  PETER SMITH",
        "Anna Brown  ",
        "georgi dimitrov"
    ],
    "salary": [
        "2500",
        "3200",
        "unknown",
        "2100",
        "4000"
    ]
})

df["name"] = df["name"].str.strip().str.title()
df["salary"] = pd.to_numeric(df["salary"], errors="coerce")
df.loc[df["salary"].isna()]
np.nanmean(df["salary"])

## Task 62

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna",
        "Georgi", "Elena", "Nikolay", "Viktor"
    ],
    "salary": [
        2500, 3200, 2800, 2100,
        4000, 3500, 2700, 4500
    ],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing", "IT"
    ],
    "years_experience": [
        2, 6, 4, 1,
        10, 8, 3, 12
    ]
})
```

Use `map()` and dictionary to transform:
```text
IT → Technology
HR → Human Resources
Marketing → Marketing
```

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna",
        "Georgi", "Elena", "Nikolay", "Viktor"
    ],
    "salary": [
        2500, 3200, 2800, 2100,
        4000, 3500, 2700, 4500
    ],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing", "IT"
    ],
    "years_experience": [
        2, 6, 4, 1,
        10, 8, 3, 12
    ]
})

df["department"] = df["department"].map(
    {
        "IT": "Technology",
        "HR": "Human Resources",
        "Marketing": "Marketing"
    }
)

df

## Task 63

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna",
        "Georgi", "Elena", "Nikolay", "Viktor"
    ],
    "salary": [
        2500, 3200, 2800, 2100,
        4000, 3500, 2700, 4500
    ],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing", "IT"
    ],
    "years_experience": [
        2, 6, 4, 1,
        10, 8, 3, 12
    ]
})
```

Use `replace()` and dictionary to transform:
```text
IT → Technology
HR → Human Resources
Marketing → Marketing
```

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna",
        "Georgi", "Elena", "Nikolay", "Viktor"
    ],
    "salary": [
        2500, 3200, 2800, 2100,
        4000, 3500, 2700, 4500
    ],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing", "IT"
    ],
    "years_experience": [
        2, 6, 4, 1,
        10, 8, 3, 12
    ]
})

df["department"] = df["department"].replace(
    {
        "IT": "Technology",
        "HR": "Human Resources"
    }
)

df

## Task 64

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna",
        "Georgi", "Elena", "Nikolay", "Viktor"
    ],
    "salary": [
        2500, 3200, 2800, 2100,
        4000, 3500, 2700, 4500
    ],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing", "IT"
    ],
    "years_experience": [
        2, 6, 4, 1,
        10, 8, 3, 12
    ]
})
```

Use `map()` with lambda to increase all salaries by 10%.

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna",
        "Georgi", "Elena", "Nikolay", "Viktor"
    ],
    "salary": [
        2500, 3200, 2800, 2100,
        4000, 3500, 2700, 4500
    ],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing", "IT"
    ],
    "years_experience": [
        2, 6, 4, 1,
        10, 8, 3, 12
    ]
})

df["salary"] = df["salary"].map(lambda x: x * 1.1)

df

## Task 65

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna",
        "Georgi", "Elena", "Nikolay", "Viktor"
    ],
    "salary": [
        2500, 3200, 2800, 2100,
        4000, 3500, 2700, 4500
    ],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing", "IT"
    ],
    "years_experience": [
        2, 6, 4, 1,
        10, 8, 3, 12
    ]
})
```

Create a column `salary_after_bonus` that contains salary + 15%.

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna",
        "Georgi", "Elena", "Nikolay", "Viktor"
    ],
    "salary": [
        2500, 3200, 2800, 2100,
        4000, 3500, 2700, 4500
    ],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing", "IT"
    ],
    "years_experience": [
        2, 6, 4, 1,
        10, 8, 3, 12
    ]
})

df["salary_after_bonus"] = df["salary"] * 1.15
df

## Task 66

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna",
        "Georgi", "Elena", "Nikolay", "Viktor"
    ],
    "salary": [
        2500, 3200, 2800, 2100,
        4000, 3500, 2700, 4500
    ],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing", "IT"
    ],
    "years_experience": [
        2, 6, 4, 1,
        10, 8, 3, 12
    ]
})
```

Create a function:

```python
def salary_category(salary):
```
that returns:
- salary < 2500 → Low
- 2500–3499 → Medium
- salary >= 3500 → High

Then do the same operation using a `lambda` function   
Use `apply()`.

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna",
        "Georgi", "Elena", "Nikolay", "Viktor"
    ],
    "salary": [
        2500, 3200, 2800, 2100,
        4000, 3500, 2700, 4500
    ],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing", "IT"
    ],
    "years_experience": [
        2, 6, 4, 1,
        10, 8, 3, 12
    ]
})

def salary_category(salary):
    if salary < 2500:
        return "Low"
    elif salary < 3499:
        return "Medium"
    else:
        return "High"



df["salary_category"] = df["salary"].apply(salary_category)

df["salary_category_lambda"] = df["salary"].apply(
    lambda salary: "Low" if salary < 2500
    else "Medium" if salary < 3500
    else "High"
)

df

## Task 67

Given:
```python
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna",
        "Georgi", "Elena", "Nikolay", "Viktor"
    ],
    "salary": [
        2500, 3200, 2800, 2100,
        4000, 3500, 2700, 4500
    ],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing", "IT"
    ],
    "years_experience": [
        2, 6, 4, 1,
        10, 8, 3, 12
    ]
})
```

Create column `is_senior` where the employee is Senior only if:
- salary >= 3000 AND years_experience >= 5

Here use:   
df.apply(..., axis=1)

In [ ]:
df = pd.DataFrame({
    "name": [
        "Ivan", "Maria", "Peter", "Anna",
        "Georgi", "Elena", "Nikolay", "Viktor"
    ],
    "salary": [
        2500, 3200, 2800, 2100,
        4000, 3500, 2700, 4500
    ],
    "department": [
        "IT", "HR", "IT", "Marketing",
        "IT", "HR", "Marketing", "IT"
    ],
    "years_experience": [
        2, 6, 4, 1,
        10, 8, 3, 12
    ]
})

def is_senior(row):
    return (
        row["salary"] >= 3000
        and row["years_experience"] >= 5
    )

df["is_senior"] = df.apply(is_senior, axis=1)

df

## Task 68

Given:
```python
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": [
        "Ivan", "Maria", "Peter",
        "Anna", "Georgi", "Elena"
    ],
    "department_id": [
        10, 20, 10, 30, 40, 20
    ],
    "salary": [
        2500, 3200, 2800,
        2100, 4000, 3500
    ]
})

departments = pd.DataFrame({
    "department_id": [10, 20, 30, 50],
    "department": [
        "IT", "HR", "Marketing", "Finance"
    ],
    "location": [
        "Sofia", "Sofia", "Plovdiv", "Varna"
    ]
})
```

Do a `merge()` between:
- employees
- departments

using:
`on="department_id"`

and see the result.

In [ ]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": [
        "Ivan", "Maria", "Peter",
        "Anna", "Georgi", "Elena"
    ],
    "department_id": [
        10, 20, 10, 30, 40, 20
    ],
    "salary": [
        2500, 3200, 2800,
        2100, 4000, 3500
    ]
})

departments = pd.DataFrame({
    "department_id": [10, 20, 30, 50],
    "department": [
        "IT", "HR", "Marketing", "Finance"
    ],
    "location": [
        "Sofia", "Sofia", "Plovdiv", "Varna"
    ]
})

result = employees.merge(
    departments,
    on="department_id"
)

result

## Task 69

Given:
```python
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": [
        "Ivan", "Maria", "Peter",
        "Anna", "Georgi", "Elena"
    ],
    "department_id": [
        10, 20, 10, 30, 40, 20
    ],
    "salary": [
        2500, 3200, 2800,
        2100, 4000, 3500
    ]
})

departments = pd.DataFrame({
    "department_id": [10, 20, 30, 50],
    "department": [
        "IT", "HR", "Marketing", "Finance"
    ],
    "location": [
        "Sofia", "Sofia", "Plovdiv", "Varna"
    ]
})
```

Do a `merge()` between:
- employees
- departments

using:
`on="department_id"` and `how="left"`

and see the result. Check what happens to Georgi.

In [ ]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": [
        "Ivan", "Maria", "Peter",
        "Anna", "Georgi", "Elena"
    ],
    "department_id": [
        10, 20, 10, 30, 40, 20
    ],
    "salary": [
        2500, 3200, 2800,
        2100, 4000, 3500
    ]
})

departments = pd.DataFrame({
    "department_id": [10, 20, 30, 50],
    "department": [
        "IT", "HR", "Marketing", "Finance"
    ],
    "location": [
        "Sofia", "Sofia", "Plovdiv", "Varna"
    ]
})

left_join = employees.merge(
    departments,
    how="left",
    on="department_id"
)

left_join

## Task 70

Given:
```python
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": [
        "Ivan", "Maria", "Peter",
        "Anna", "Georgi", "Elena"
    ],
    "department_id": [
        10, 20, 10, 30, 40, 20
    ],
    "salary": [
        2500, 3200, 2800,
        2100, 4000, 3500
    ]
})

departments = pd.DataFrame({
    "department_id": [10, 20, 30, 50],
    "department": [
        "IT", "HR", "Marketing", "Finance"
    ],
    "location": [
        "Sofia", "Sofia", "Plovdiv", "Varna"
    ]
})
```

Do a `merge()` between:
- employees
- departments

using:
`on="department_id"` and `how="right"`

and see the result. Check what happens with department_id = 50.

In [ ]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": [
        "Ivan", "Maria", "Peter",
        "Anna", "Georgi", "Elena"
    ],
    "department_id": [
        10, 20, 10, 30, 40, 20
    ],
    "salary": [
        2500, 3200, 2800,
        2100, 4000, 3500
    ]
})

departments = pd.DataFrame({
    "department_id": [10, 20, 30, 50],
    "department": [
        "IT", "HR", "Marketing", "Finance"
    ],
    "location": [
        "Sofia", "Sofia", "Plovdiv", "Varna"
    ]
})

right_join = employees.merge(
    departments,
    how="right",
    on="department_id"
)

right_join

## Task 71

Given:
```python
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": [
        "Ivan", "Maria", "Peter",
        "Anna", "Georgi", "Elena"
    ],
    "department_id": [
        10, 20, 10, 30, 40, 20
    ],
    "salary": [
        2500, 3200, 2800,
        2100, 4000, 3500
    ]
})

departments = pd.DataFrame({
    "department_id": [10, 20, 30, 50],
    "department": [
        "IT", "HR", "Marketing", "Finance"
    ],
    "location": [
        "Sofia", "Sofia", "Plovdiv", "Varna"
    ]
})
```

Do a `merge()` between:
- employees
- departments

using:
`on="department_id"` and `how="outer"`

and see the result. Here you should see both types of mismatches:
- employee → no department
- department → no employee

In [ ]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": [
        "Ivan", "Maria", "Peter",
        "Anna", "Georgi", "Elena"
    ],
    "department_id": [
        10, 20, 10, 30, 40, 20
    ],
    "salary": [
        2500, 3200, 2800,
        2100, 4000, 3500
    ]
})

departments = pd.DataFrame({
    "department_id": [10, 20, 30, 50],
    "department": [
        "IT", "HR", "Marketing", "Finance"
    ],
    "location": [
        "Sofia", "Sofia", "Plovdiv", "Varna"
    ]
})

outer_join = employees.merge(
    departments,
    how="outer",
    on="department_id"
)

outer_join

## Task 72

Given:
```python
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": [
        "Ivan", "Maria", "Peter",
        "Anna", "Georgi", "Elena"
    ],
    "department_id": [
        10, 20, 10, 30, 40, 20
    ],
    "salary": [
        2500, 3200, 2800,
        2100, 4000, 3500
    ]
})
```

Do a left merge so that you get a table:
- name
- salary
- department
- location

Then sort the employees by:
- salary descending

In [ ]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": [
        "Ivan", "Maria", "Peter",
        "Anna", "Georgi", "Elena"
    ],
    "department_id": [
        10, 20, 10, 30, 40, 20
    ],
    "salary": [
        2500, 3200, 2800,
        2100, 4000, 3500
    ]
})

departments = pd.DataFrame({
    "department_id": [10, 20, 30, 50],
    "department": [
        "IT", "HR", "Marketing", "Finance"
    ],
    "location": [
        "Sofia", "Sofia", "Plovdiv", "Varna"
    ]
})

result = employees.merge(departments, how="left", on="department_id")[["name", "salary", "department", "location"]]
result.sort_values(by="salary", ascending=False, inplace=True)
result


## Task 73

Given:
```python
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": [
        "Ivan", "Maria", "Peter",
        "Anna", "Georgi", "Elena"
    ],
    "department_id": [
        10, 20, 10, 30, 40, 20
    ],
    "salary": [
        2500, 3200, 2800,
        2100, 4000, 3500
    ]
})
```

Create a copy:

```python
departments_2 = departments.rename(
columns={"department_id": "dept_id"}
)
```

Now do a merge between:

```text
employees.department_id
departments_2.dept_id
```
Here you should use:

```text
left_on=
right_on=
```

In [ ]:
employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": [
        "Ivan", "Maria", "Peter",
        "Anna", "Georgi", "Elena"
    ],
    "department_id": [
        10, 20, 10, 30, 40, 20
    ],
    "salary": [
        2500, 3200, 2800,
        2100, 4000, 3500
    ]
})

departments_2 = departments.rename(
columns={"department_id": "dept_id"}
)

result = employees.merge(
    departments_2,
    left_on="department_id",
    right_on="dept_id"
    )

result

# Task 74

Given:
```python
employees_1 = pd.DataFrame({
"name": ["Ivan", "Maria", "Peter"],
"salary": [2500, 3200, 2800]
})

employees_2 = pd.DataFrame({
"name": ["Anna", "Georgi", "Elena"],
"salary": [2100, 4000, 3500]
})
```

Use `concat()` so that you get one DataFrame with all 6 employees.
The index should be:
```text
0
1
2
3
4
5
```

In [ ]:
employees_1 = pd.DataFrame({
"name": ["Ivan", "Maria", "Peter"],
"salary": [2500, 3200, 2800]
})

employees_2 = pd.DataFrame({
"name": ["Anna", "Georgi", "Elena"],
"salary": [2100, 4000, 3500]
})

pd.concat([employees_1, employees_2], ignore_index=True)

# Task 75

Given:
```python
names = pd.DataFrame({
"name": ["Ivan", "Maria", "Peter"]
})

salaries = pd.DataFrame({
"salary": [2500, 3200, 2800]
})
```

Use `concat()` to create a dataset about every employee and his salary:

```text
name salary
0 Ivan 2500
1 Maria 3200
2 Peter 2800
```

In [ ]:
names = pd.DataFrame({
"name": ["Ivan", "Maria", "Peter"]
})

salaries = pd.DataFrame({
"salary": [2500, 3200, 2800]
})

pd.concat([names, salaries], axis=1)


## Task 76

Given:
```python
employees_basic = pd.DataFrame({
"name": ["Ivan", "Maria"],
"salary": [2500, 3200]
})

employees_extra = pd.DataFrame({
"name": ["Peter", "Anna"],
"department": ["IT", "HR"]
})
```
Use `concat()` so that you get all employees and all columns.

What will appear in the places where data is missing?
What will happen if you use `inner` join ?

In [ ]:
employees_basic = pd.DataFrame({
"name": ["Ivan", "Maria"],
"salary": [2500, 3200]
})

employees_extra = pd.DataFrame({
"name": ["Peter", "Anna"],
"department": ["IT", "HR"]
})

pd.concat([employees_basic, employees_extra], join="outer", ignore_index=True)
pd.concat([employees_basic, employees_extra], join="inner", ignore_index=True)

# Task 77

Given:
```python
employees_january = pd.DataFrame({
    "employee_id": [1, 2, 3],
    "name": ["Ivan", "Maria", "Peter"],
    "salary": [2500, 3200, 2800]
})

employees_february = pd.DataFrame({
    "employee_id": [4, 5, 6],
    "name": ["Anna", "Georgi", "Elena"],
    "salary": [2100, 4000, 3500]
})
```

Create a DataFrame `all_employees` that contains all employees.   
Then:
- Use ignore_index=True.
- Sort by salary in descending order.
- Calculate the average salary.

In [ ]:
employees_january = pd.DataFrame({
    "employee_id": [1, 2, 3],
    "name": ["Ivan", "Maria", "Peter"],
    "salary": [2500, 3200, 2800]
})

employees_february = pd.DataFrame({
    "employee_id": [4, 5, 6],
    "name": ["Anna", "Georgi", "Elena"],
    "salary": [2100, 4000, 3500]
})

all_employees = pd.concat([employees_january, employees_february], ignore_index=True).sort_values("salary", ascending=False)
all_employees["salary"].mean()

# Task 78

Given:
```python
it = pd.DataFrame({
    "name": ["Ivan", "Peter", "Georgi"],
    "salary": [2500, 2800, 4000],
    "department": ["IT", "IT", "IT"]
})

hr = pd.DataFrame({
    "name": ["Maria", "Anna", "Elena"],
    "salary": [3200, 2100, 3500],
    "department": ["HR", "HR", "HR"]
})
```

Create a DataFrame `employees` that contains all employees.

Then find:
- the total number of employees
- the average salary
- the highest salary
- the number of employees in each department
- the average salary by department

In [ ]:
it = pd.DataFrame({
    "name": ["Ivan", "Peter", "Georgi"],
    "salary": [2500, 2800, 4000],
    "department": ["IT", "IT", "IT"]
})

hr = pd.DataFrame({
    "name": ["Maria", "Anna", "Elena"],
    "salary": [3200, 2100, 3500],
    "department": ["HR", "HR", "HR"]
})

employees = pd.concat([it, hr], ignore_index=True)
len(employees)
employees["salary"].mean()
employees["salary"].max()
employees.groupby("department").size()
employees.groupby("department")["salary"].mean()

# Task 79

Given:
```python
employees = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena",
             "Dimitar", "Nina", "Alex", "Laura"],
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales",
                   "IT", "HR", "Sales", "IT"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "salary": [3000, 3500, 2800, 3200, 2500, 2900,
               3300, 3100, 2700, 3600],
    "years_experience": [2, 5, 1, 6, 2, 4, 4, 5, 3, 7]
})
```
Create a pivot table that shows the average salary for each department

In [27]:
employees = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena",
             "Dimitar", "Nina", "Alex", "Laura"],
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales",
                   "IT", "HR", "Sales", "IT"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "salary": [3000, 3500, 2800, 3200, 2500, 2900,
               3300, 3100, 2700, 3600],
    "years_experience": [2, 5, 1, 6, 2, 4, 4, 5, 3, 7]
})

pd.pivot_table(employees,
               values="salary",
               index="department",
               aggfunc="mean"
             )

                 salary
department
HR          3033.333333
IT          3350.000000
Sales       2700.000000

# Task 80

Given:
```python
employees = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena",
             "Dimitar", "Nina", "Alex", "Laura"],
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales",
                   "IT", "HR", "Sales", "IT"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "salary": [3000, 3500, 2800, 3200, 2500, 2900,
               3300, 3100, 2700, 3600],
    "years_experience": [2, 5, 1, 6, 2, 4, 4, 5, 3, 7]
})
```

Create a pivot table that shows the average salary by `department` and `gender`

In [28]:
employees = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena",
             "Dimitar", "Nina", "Alex", "Laura"],
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales",
                   "IT", "HR", "Sales", "IT"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "salary": [3000, 3500, 2800, 3200, 2500, 2900,
               3300, 3100, 2700, 3600],
    "years_experience": [2, 5, 1, 6, 2, 4, 4, 5, 3, 7]
})

pd.pivot_table(employees,
               values="salary",
               index="department",
               columns="gender",
               aggfunc="mean"

)

gender           F       M
department
HR          3150.0  2800.0
IT          3550.0  3150.0
Sales       2900.0  2600.0

# Task 81

Given:
```python
employees = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena",
             "Dimitar", "Nina", "Alex", "Laura"],
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales",
                   "IT", "HR", "Sales", "IT"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "salary": [3000, 3500, 2800, 3200, 2500, 2900,
               3300, 3100, 2700, 3600],
    "years_experience": [2, 5, 1, 6, 2, 4, 4, 5, 3, 7]
})
```

Create a pivot table that shows the number of employees by `department` and `gender`

In [30]:
employees = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena",
             "Dimitar", "Nina", "Alex", "Laura"],
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales",
                   "IT", "HR", "Sales", "IT"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "salary": [3000, 3500, 2800, 3200, 2500, 2900,
               3300, 3100, 2700, 3600],
    "years_experience": [2, 5, 1, 6, 2, 4, 4, 5, 3, 7]
})

pd.pivot_table(employees,
               values="salary",
               index="department",
               columns="gender",
               aggfunc="count")

gender      F  M
department
HR          2  1
IT          2  2
Sales       1  2

# Task 82

Given:
```python
employees = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena",
             "Dimitar", "Nina", "Alex", "Laura"],
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales",
                   "IT", "HR", "Sales", "IT"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "salary": [3000, 3500, 2800, 3200, 2500, 2900,
               3300, 3100, 2700, 3600],
    "years_experience": [2, 5, 1, 6, 2, 4, 4, 5, 3, 7]
})
```

Create a pivot table that shows the total payroll (salary) by department and gender.

In [31]:
employees = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena",
             "Dimitar", "Nina", "Alex", "Laura"],
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales",
                   "IT", "HR", "Sales", "IT"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "salary": [3000, 3500, 2800, 3200, 2500, 2900,
               3300, 3100, 2700, 3600],
    "years_experience": [2, 5, 1, 6, 2, 4, 4, 5, 3, 7]
})

pd.pivot_table(employees,
               values="salary",
               index="department",
               columns="gender",
               aggfunc="sum",
               margins=True)

gender          F      M    All
department
HR           6300   2800   9100
IT           7100   6300  13400
Sales        2900   5200   8100
All         16300  14300  30600

# Task 83

Make a pivot table that shows for each department:
- average salary
- maximum salary
- minimum salary

In [32]:
employees = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena",
             "Dimitar", "Nina", "Alex", "Laura"],
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales",
                   "IT", "HR", "Sales", "IT"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "salary": [3000, 3500, 2800, 3200, 2500, 2900,
               3300, 3100, 2700, 3600],
    "years_experience": [2, 5, 1, 6, 2, 4, 4, 5, 3, 7]
})

pd.pivot_table(
    employees,
    values="salary",
    index="department",
    aggfunc=["mean", "max", "min"]
)

                   mean    max    min
                 salary salary salary
department
HR          3033.333333   3200   2800
IT          3350.000000   3600   3000
Sales       2700.000000   2900   2500

# Task 84

Given:
```python
employees = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena",
             "Dimitar", "Nina", "Alex", "Laura"],
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales",
                   "IT", "HR", "Sales", "IT"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "salary": [3000, 3500, 2800, 3200, 2500, 2900,
               3300, 3100, 2700, 3600],
    "years_experience": [2, 5, 1, 6, 2, 4, 4, 5, 3, 7]
})
```
Make a pivot table:
average salary by `department` and `gender`, with missing combinations being 0 instead of NaN.

In [33]:
employees = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena",
             "Dimitar", "Nina", "Alex", "Laura"],
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales",
                   "IT", "HR", "Sales", "IT"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "salary": [3000, 3500, 2800, 3200, 2500, 2900,
               3300, 3100, 2700, 3600],
    "years_experience": [2, 5, 1, 6, 2, 4, 4, 5, 3, 7]
})

pd.pivot_table(
    employees,
    values="salary",
    index="department",
    columns="gender",
    aggfunc="mean",
    fill_value=0
)

gender           F       M
department
HR          3150.0  2800.0
IT          3550.0  3150.0
Sales       2900.0  2600.0


# Task 85

Given:
```python
employees = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena",
             "Dimitar", "Nina", "Alex", "Laura"],
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales",
                   "IT", "HR", "Sales", "IT"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "salary": [3000, 3500, 2800, 3200, 2500, 2900,
               3300, 3100, 2700, 3600],
    "years_experience": [2, 5, 1, 6, 2, 4, 4, 5, 3, 7]
})
```

Make a pivot table that shows:
average salary and average years of experience by department and gender.

In [ ]:
employees = pd.DataFrame({
    "name": ["Ivan", "Maria", "Peter", "Anna", "Georgi", "Elena",
             "Dimitar", "Nina", "Alex", "Laura"],
    "department": ["IT", "IT", "HR", "HR", "Sales", "Sales",
                   "IT", "HR", "Sales", "IT"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "salary": [3000, 3500, 2800, 3200, 2500, 2900,
               3300, 3100, 2700, 3600],
    "years_experience": [2, 5, 1, 6, 2, 4, 4, 5, 3, 7]
})

pd.pivot_table(
    employees,
    values=["salary", "years_experience"],
    index="department",
    columns="gender",
    aggfunc="mean"
    )

            salary         years_experience
gender           F       M                F    M
department
HR          3150.0  2800.0              5.5  1.0
IT          3550.0  3150.0              6.0  3.0
Sales       2900.0  2600.0              4.0  2.5